services:
  nodeapp:
    image: node-app:v1
    ports:
      - 3000:3000
  
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres